src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Repository\InvoiceRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InvoiceRepository::class)
 */
class Invoice
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="decimal", precision=7, scale=2)
     */
    private $htAmount;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getHtAmount(): ?string
    {
        return $this->htAmount;
    }

    public function setHtAmount(string $htAmount): self
    {
        $this->htAmount = $htAmount;

        return $this;
    }

    public function getTtcAmount(): ?string
    {
        return $this->htAmount * 1.2;
    }
}

src/Form/InvoiceType.php
<?php

namespace App\Form;

use App\Entity\Invoice;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InvoiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Désignation de la facture'
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description de la facture'
            ])
            ->add('htAmount',NumberType::class, [
                'label' => 'Prix Hors Taxe (en €)'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Invoice::class,
        ]);
    }
}

src/Controller/InvoiceController.php
<?php

namespace App\Controller;

use App\Entity\Invoice;
use App\Form\InvoiceType;
use App\Repository\InvoiceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/invoice")
 */
class InvoiceController extends AbstractController
{
    /**
     * @Route("/new", name="app_invoice_new", methods={"GET", "POST"})
     */
    public function new(Request $request, InvoiceRepository $invoiceRepository): Response
    {
        $invoice = new Invoice();
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $invoiceRepository->add($invoice);
            return $this->redirectToRoute('home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('invoice/new.html.twig', [
            'invoice' => $invoice,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_invoice_show", methods={"GET"})
     */
    public function show(Invoice $invoice): Response
    {
        return $this->render('invoice/show.html.twig', [
            'invoice' => $invoice,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_invoice_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Invoice $invoice, InvoiceRepository $invoiceRepository): Response
    {
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $invoiceRepository->add($invoice);
            return $this->redirectToRoute('home', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('invoice/edit.html.twig', [
            'invoice' => $invoice,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_invoice_delete", methods={"POST"})
     */
    public function delete(Request $request, Invoice $invoice, InvoiceRepository $invoiceRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$invoice->getId(), $request->request->get('_token'))) {
            $invoiceRepository->remove($invoice);
        }

        return $this->redirectToRoute('home', [], Response::HTTP_SEE_OTHER);
    }
}

templates/invoice/_delete_form.html.twig
<form method="post" action="{{ path('app_invoice_delete', {'id': invoice.id}) }}" onsubmit="return confirm('Êtes-vous certains de vouloir supprimer cet élément ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ invoice.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/invoice/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/invoice/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une facture{% endblock %}

{% block body %}
    <div class="container">
        <h1>Modifier une facture</h1>

        {{ include('invoice/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

        <a href="{{ path('home') }}">Retour à l'accueil</a>

        {{ include('invoice/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/invoice/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle facture{% endblock %}

{% block body %}
    <div class="container">
        <h1>Générer une nouvelle facture</h1>

        {{ include('invoice/_form.html.twig') }}

        <a href="{{ path('home') }}">Revenir à la page d'accueil</a>
    </div>

{% endblock %}

templates/invoice/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Invoice{% endblock %}

{% block body %}
    <h1>Facture</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>N°</th>
                <td>{{ invoice.id }}</td>
            </tr>
            <tr>
                <th>Désignation</th>
                <td>{{ invoice.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ invoice.description }}</td>
            </tr>
            <tr>
                <th>Prix Ht</th>
                <td>{{ invoice.htAmount }} €</td>
            </tr>
            <tr>
                <th>Prix TTC</th>
                <td>{{ invoice.ttcAmount }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('home') }}" class="btn btn-primary">Retour à l'accueil</a>

    <a href="{{ path('app_invoice_edit', {'id': invoice.id}) }}" class="btn btn-success">Modifier</a>

    {{ include('invoice/_delete_form.html.twig') }}
{% endblock %}